Repository canonical/discourse-k8s-operator, pull requests merged in 2023-10, with the labels that each got.

#113 Various improvements to the docs
  README.md
  docs/Reference/.gitkeep
  docs/Tutorial/contributing.md
  docs/Tutorial/hostname-configuration.md
  docs/explanation/charm-architecture.md
  docs/how-to/configure-container.md
  docs/how-to/configure-hostname.md
  docs/how-to/configure-s3.md
  docs/how-to/configure-saml.md
  docs/how-to/configure-smtp.md
  docs/how-to/contribute.md
  docs/how-to/upgrade.md
  docs/index.md
  docs/reference/integrations.md
  docs/tutorial/getting-started.md
Labels: documentation, Libraries: OK, trivial

#119 feat(runners): Use edge runners
  .github/workflows/test.yaml
Labels: Libraries: Out of sync, trivial

#120 docs(start): Add section on extensions
  docs/tutorial/getting-started.md
Labels: Libraries: Out of sync, trivial

#124 ci(digest): Add digest pinning
  renovate.json
Labels: Libraries: OK, trivial

#126 Add --use-existing feature to integ tests
  src/charm.py
  tests/conftest.py
  tests/integration/conftest.py
Labels: Libraries: OK, trivial

#125 Pin plugins to specific commits
  .github/workflows/test.yaml
  .licenserc.yaml
  discourse_rock/bundler/config
  discourse_rock/rockcraft.yaml
  src/charm.py
Labels: Libraries: OK, trivial, urgent

#130 Add logging during setup process and ensure we're reacting to start hook
  pyproject.toml
  src/charm.py
  tests/unit/test_charm.py
Labels: Libraries: OK, urgent

#133 Change permissive level
  src/charm.py
Labels: Libraries: OK, trivial, urgent

#128 Add some pebble checks
  src/charm.py
Labels: Libraries: OK, trivial
