Repository canonical/discourse-k8s-operator, pull requests merged in 2023-12, with the labels that each got.

#143 Use juju 3 in integ tests
  .github/workflows/integration_test.yaml
  .github/workflows/integration_test_with_secrets.yaml
  tests/integration/test_charm.py
  tox.ini
Labels: Libraries: OK, trivial

#149 Make sure to setup discourse on database created event
  src/charm.py
  tests/unit/helpers.py
  tests/unit/test_charm.py
Labels: Libraries: Out of sync, trivial

#152 Add proxy juju env support
  src/charm.py
  tests/unit/test_charm.py
Labels: Libraries: Out of sync, trivial

#141 feat: Discourse v3 rock
  discourse_rock/bundler/config
  discourse_rock/patches/lp1903695.patch
  discourse_rock/rockcraft.yaml
  src/charm.py
Labels: Libraries: OK, trivial

#153 chore(github): Add PR Template
  .github/pull_request_template.md
Labels: Libraries: OK, trivial

#156 fix(ci): Pin protobuf
  tox.ini
Labels: bug, trivial

#155 Feat/v3 plugin updates
  discourse_rock/rockcraft.yaml
Labels: trivial

#157 chore(plugins): Add new plugins
  discourse_rock/rockcraft.yaml
Labels: trivial

#158 Fix/Update plugins
  discourse_rock/rockcraft.yaml
Labels: Libraries: Out of sync, trivial

#159 fix(perms): Run unicorn as non-root user
  src/charm.py
Labels: bug, Libraries: Out of sync, trivial
