Repository canonical/discourse-k8s-operator, pull requests merged in 2024-09, with the labels that each got.

#283 Feat/ Redis HA fix
  src-docs/charm.py.md
  src/charm.py
  tests/unit/helpers.py
  tests/unit/test_charm.py
  tox.ini
Labels: enhancement, good first issue, Libraries: OK, trivial

#290 Update tutorial
  docs/tutorial.md
Labels: documentation, Libraries: OK, trivial

#291 Standardise how-to guides and reference pages
  docs/index.md
  docs/reference/actions.md
  docs/reference/configurations.md
  docs/reference/integrations.md
Labels: documentation, Libraries: OK, trivial

#287 Feat: Fixed db migration issues from v3.2.0 to 3.3.0
  .github/workflows/integration_test.yaml
  charmcraft.yaml
  discourse_rock/patches/db_migrations.patch
  discourse_rock/rockcraft.yaml
  testing_database/creating-the-testing-database.md
  testing_database/testing_database.sql
  tests/integration/test_db_migration.py
Labels: Libraries: OK, trivial
