Repository canonical/discourse-k8s-operator, pull requests merged in 2024-01, with the labels that each got.

#162 Fix commit of discourse-templates plugin (& other fixes)
  actions.yaml
  charmcraft.yaml
  config.yaml
  discourse_rock/rockcraft.yaml
  discourse_rock/scripts/app_launch.sh
  generate-src-docs.sh
  lib/charms/data_platform_libs/v0/data_interfaces.py
  lib/charms/nginx_ingress_integrator/v0/nginx_route.py
  localstack-installation.sh
  metadata.yaml
  pyproject.toml
  src/charm.py
  src/database.py
  tests/__init__.py
  tests/conftest.py
  tests/integration/__init__.py
  tests/integration/conftest.py
  tests/integration/test_charm.py
  tests/integration/types.py
  tests/unit/__init__.py
  tests/unit/helpers.py
  tests/unit/test_charm.py
  tox.ini
Labels: Libraries: Out of sync, trivial

#165 fix(postgresql): Add pg_dump
  discourse_rock/rockcraft.yaml
Labels: Libraries: Out of sync, trivial

#166 Fix/add pg dump
  discourse_rock/rockcraft.yaml
Labels: bug, Libraries: Out of sync, trivial

#170 Add Rails console docs
  docs/how-to/access--the-rails-console.md
Labels: Libraries: Out of sync

#171 Add rolling-ops library
  lib/charms/rolling_ops/v0/rollingops.py
  metadata.yaml
  src-docs/charm.py.md
  src/charm.py
  tests/unit/test_charm.py
Labels: Libraries: Out of sync, trivial

#173 Fix trivy exit-code
  trivy.yaml
Labels: Libraries: Out of sync, trivial

#177 Fix rolling restart by adding a dedicated callback method
  src/charm.py
Labels: Libraries: Out of sync, trivial

#181 Create bot_pr_approval.yaml
  .github/workflows/bot_pr_approval.yaml
Labels: Libraries: Out of sync, trivial

#184 Fix linting
  src/charm.py
  tests/unit/helpers.py
Labels: Libraries: Out of sync, trivial
