Repository canonical/discourse-k8s-operator, pull requests merged in 2024-08, with the labels that each got.

#276 Chat integration plugin
  discourse_rock/rockcraft.yaml
  tests/integration/conftest.py
Labels: Libraries: OK, trivial

#278 feat: Discourse 3.3.0 upgrade
  discourse_rock/patches/sigterm.patch
  discourse_rock/rockcraft.yaml
Labels: enhancement, Libraries: OK, trivial

#281 Update docs
  docs/how-to/access--the-rails-console.md
  docs/how-to/configure-container.md
  docs/how-to/configure-s3.md
  docs/how-to/configure-saml.md
  docs/how-to/contribute.md
  docs/index.md
  docs/tutorial.md
Labels: documentation, Libraries: OK, trivial
