Repository canonical/discourse-k8s-operator, pull requests merged in 2025-06, with the labels that each got.

#334 docs/ISD-3460: Fixing vale errors
  .github/pull_request_template.md
  README.md
  docs/explanation/charm-architecture.md
  docs/how-to/configure-hostname.md
  docs/how-to/configure-s3.md
  docs/index.md
  docs/reference/integrations.md
  docs/tutorial.md
  lib/charms/data_platform_libs/v0/data_interfaces.py
  src-docs/charm.py.md
  src-docs/database.py.md
  testing_database/creating-the-testing-database.md
Labels: Libraries: Out of sync

#338 ISD-1817 Add ability to automatically configure cors_origin
  CODEOWNERS
  config.yaml
  docs/how-to/configure-container.md
  docs/tutorial.md
  pyproject.toml
  src/charm.py
  tests/integration/conftest.py
  tests/integration/test_charm.py
  tests/integration/test_saml.py
  tests/integration/test_users.py
  tests/unit/conftest.py
  tests/unit/test_charm.py
  tests/unit_harness/__init__.py
  tests/unit_harness/helpers.py
  tests/unit_harness/test_charm.py
  tox.ini
Labels: Libraries: Out of sync

#340 Update .trivyignore
  .trivyignore
Labels: Libraries: Out of sync, trivial

#339 Add Service Health dashboard
  docs/changelog.md
  src/grafana_dashboards/discourse_service_health.json
Labels: Libraries: Out of sync, trivial

#342 Fix databasource in discourse_service_health.
  src/grafana_dashboards/discourse_service_health.json
Labels: bug, Libraries: OK, trivial

#344 Add tox lint-docs target to check broken links
  docs/explanation/charm-architecture.md
  docs/how-to/backup-and-restore.md
  docs/index.md
  docs/reference/integrations.md
  docs/tutorial.md
  tox.ini
Labels: documentation, Libraries: OK

#341 feat/ISD-3609: Add multi-level category setting to charm config
  config.yaml
  src/charm.py
  tests/unit_harness/test_charm.py
Labels: Libraries: OK, trivial
